"""New Migration

Revision ID: f255c81e1d2c
Revises: 
Create Date: 2022-04-26 15:50:50.972830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f255c81e1d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pelanggan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelanggan_email'), 'pelanggan', ['email'], unique=True)
    op.create_index(op.f('ix_pelanggan_id'), 'pelanggan', ['id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('nama_product', sa.String(length=255), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=True),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('pesanan',
    sa.Column('id_pesanan', sa.BigInteger(), nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('id_produk', sa.BigInteger(), nullable=True),
    sa.Column('nama_pemesan', sa.String(length=255), nullable=True),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('volume_produk', sa.Integer(), nullable=True),
    sa.Column('total_harga', sa.Integer(), nullable=True),
    sa.Column('status_pesanan', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_produk'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['pelanggan.id'], ),
    sa.PrimaryKeyConstraint('id_pesanan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesanan')
    op.drop_table('product')
    op.drop_index(op.f('ix_pelanggan_id'), table_name='pelanggan')
    op.drop_index(op.f('ix_pelanggan_email'), table_name='pelanggan')
    op.drop_table('pelanggan')
    # ### end Alembic commands ###
